name: Fake Contribution Booster

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at 12:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fake_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Fake Contributions
        run: |
          mkdir -p fake_contributions
          echo "print('Hello from Python!')" > fake_contributions/script.py
          echo "from django.http import HttpResponse\n\ndef home(request):\n    return HttpResponse('Django Contribution')" > fake_contributions/views.py
          echo "#include <iostream>\nusing namespace std;\nint main() {\n cout << 'Hello from C++!';\n return 0;\n}" > fake_contributions/main.cpp
          echo "using System;\nnamespace AspNet\n{\n class Program\n {\n static void Main()\n {\n Console.WriteLine('ASP.NET Contribution');\n }\n }\n}" > fake_contributions/Program.cs

      - name: Commit and Push Fake Contributions Randomly
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Generate a random number between 1 and 5
          COUNT=$((RANDOM % 5 + 1))

          for i in $(seq 1 $COUNT); do
            echo "// Fake commit $i on $(date)" >> fake_contributions/random_$i.cpp
            git add fake_contributions/*
            git commit -m "🔧 Fake Commit $i for Python, Django, C++, ASP.NET"
          done

          git push
