name: Daily GitHub Activity Update

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 PM UTC (Daily Update)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Daily Report
        run: |
          echo "## 📊 Daily GitHub Activity Report" > daily_report.md
          echo "" >> daily_report.md
          echo "![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=mdraiyanalam&theme=dark)" >> daily_report.md
          echo "" >> daily_report.md
          echo "📆 **Last 7 Days Contributions:**" >> daily_report.md
          echo "" >> daily_report.md
          curl -s https://github-contributions.vercel.app/api/mdraiyanalam | jq -r '.total' >> daily_report.md

      - name: Update README.md
        run: |
          sed -i '/<!-- DAILY_REPORT_START -->/,/<!-- DAILY_REPORT_END -->/c\<!-- DAILY_REPORT_START -->\n'$(cat daily_report.md)'\n<!-- DAILY_REPORT_END -->' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📊 Updated Daily GitHub Activity Report"
          git push
